### ISSUE TITLE
Compilation Issue 0

### ISSUE THREAD

**Issue by madmax76** [erichVK5/BXL2text#2]
I get many of these errors while compiling:

```
SymbolText.java:36: error: unmappable character for encoding ASCII
//??? type = always 0.
```

Problem is that in the header of some files "a bulleted list" is used and they are not translated correctly, at least not on my terminals. After removing them, these issues are solved.

Example:

```
//‚Ä¢ orientation = horizontal orientation (=0) or vertical (=1).
//‚Ä¢ type = always 0.
//‚Ä¢ unit = 0 if common to the parts. If not, the number of the part (1. .n).
//‚Ä¢ convert = 0 if common to the representations, if not 1 or 2.
```

It is present in the following files:

```
SymbolPin.java
SymbolPolyline.java
SymbolRectangle.java
SymbolText.java
```

Also  there is an empty else if that java on OSX does not seem to like:

```
Footprint.java:253: error: illegal start of expression
        else if () {
                 ^
```

After removing it, compilation proceeds correctly.

**Comment by erichVK5** [comment]
Thank you, I will amend the files accordingly.
