### ISSUE TITLE
Pines must be rotate 180º in eeschema library

### ISSUE THREAD

**Issue by lsaavedr** [erichVK5/BXL2text#4]
There is a problem with the ultra librarian file or with this excellent library

to reproduce:
$ wget http://www.ti.com/litv/pdf/MSOI002J
$ java BXLDecoder TLE2426_D_8.bxl

and check TLE2426_D_8.lib,

regards,
Luis
PD: Thanks for BXL2text!

**Comment by erichVK5** [comment]
OK, I will have a look and sort it out. It was a 50/50 bet when I implemented .lib export....

Murphy's law....

**Comment by erichVK5** [comment]
I've fixed the KiCad eeschema .lib schematic symbol pin directions generated during conversion, based on testing with the example TLE2426_D_8.bxl example provided:

![kicadlibexport](https://cloud.githubusercontent.com/assets/4311877/26617376/08e58184-4614-11e7-9936-1d1560899237.png)

Please re-open this if there are any other issues noted with pin orientation.

Cheers,

Erich.
